import type { Metadata } from 'next';
import './globals.css';
import LayoutContent from './components/LayoutContent';

export const metadata: Metadata = {
    title: 'BB Seguros',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.svg'
    }
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="overflow-hidden">
                <LayoutContent>{children}</LayoutContent>
            </body>
        </html>
    );
}
